/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrainTicket;

import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.WindowConstants;


public class Menu extends javax.swing.JFrame{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter (){
            @Override
            public void windowClosing(WindowEvent we) {
               int x = JOptionPane.showConfirmDialog(null,"Do you really want to close the app?","Close",YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
               if(x == JOptionPane.YES_OPTION){
                   we.getWindow().dispose();
                   System.out.println("Closed"); 
               }
               else System.out.println("Still Running");
         }
            
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        train_tracking = new javax.swing.JButton();
        online_ticket = new javax.swing.JButton();
        notice_board = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        mobile_ticket = new javax.swing.JButton();
        about = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        login_another = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 580));
        getContentPane().setLayout(null);

        jButton1.setText("History of Rail");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(141, 102, 120, 30);

        jButton2.setText("Train Schedule");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 110, 120, 30);

        jButton3.setText("Ticket Price");
        getContentPane().add(jButton3);
        jButton3.setBounds(141, 175, 120, 30);

        train_tracking.setText("Train Tracking");
        train_tracking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                train_trackingMouseClicked(evt);
            }
        });
        train_tracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                train_trackingActionPerformed(evt);
            }
        });
        getContentPane().add(train_tracking);
        train_tracking.setBounds(440, 170, 120, 30);

        online_ticket.setText("Buy Online Ticket");
        online_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                online_ticketMouseClicked(evt);
            }
        });
        online_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                online_ticketActionPerformed(evt);
            }
        });
        getContentPane().add(online_ticket);
        online_ticket.setBounds(140, 250, 130, 30);

        notice_board.setText("Notice Board");
        notice_board.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notice_boardMouseClicked(evt);
            }
        });
        notice_board.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notice_boardActionPerformed(evt);
            }
        });
        getContentPane().add(notice_board);
        notice_board.setBounds(440, 243, 120, 30);

        jButton7.setText("Station Map");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(140, 390, 120, 30);

        jButton8.setText("Important Numbers");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(440, 314, 140, 30);

        mobile_ticket.setText("Mobile Ticket");
        mobile_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobile_ticketMouseClicked(evt);
            }
        });
        mobile_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_ticketActionPerformed(evt);
            }
        });
        getContentPane().add(mobile_ticket);
        mobile_ticket.setBounds(140, 320, 120, 30);

        about.setText("About Us");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        getContentPane().add(about);
        about.setBounds(440, 390, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to Railway Ticketing Services Of Bangladesh");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 510, 46);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(20, 460, 73, 30);

        login_another.setText("Log in with another acc.");
        login_another.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_anotherActionPerformed(evt);
            }
        });
        getContentPane().add(login_another);
        login_another.setBounds(580, 450, 170, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\showkot\\Documents\\NetBeansProjects\\TrainTicket\\photos\\menu_final.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 790, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void notice_boardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notice_boardActionPerformed
        // TODO add your handling code here:
       // this.hide();
        
    }//GEN-LAST:event_notice_boardActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        History history = new History();
        history.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
        About pranto_showkot = new About();
        pranto_showkot.setVisible(true);
        
    }//GEN-LAST:event_aboutMouseClicked

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        //this.hide();
       
    }//GEN-LAST:event_aboutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void train_trackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_train_trackingActionPerformed
        // TODO add your handling code here:
       // this.hide();
    }//GEN-LAST:event_train_trackingActionPerformed

    private void train_trackingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_train_trackingMouseClicked
        // TODO add your handling code here:
        Browser browser = new Browser();
        BrowserView view = new BrowserView(browser);

        JFrame frame = new JFrame("Bangladesh Railway");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.add(view, BorderLayout.CENTER);
        frame.setSize(500, 400);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        browser.loadURL("C:\\Users\\showkot\\Documents\\NetBeansProjects\\TrainTicket\\train_tracking\\TTMS01.html");
    }//GEN-LAST:event_train_trackingMouseClicked

    private void online_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_online_ticketActionPerformed
        // TODO add your handling code here:
        
       // this.hide();
    }//GEN-LAST:event_online_ticketActionPerformed

    private void online_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_online_ticketMouseClicked
        // TODO add your handling code here:
        Browser browser = new Browser();
        BrowserView view = new BrowserView(browser);

        JFrame frame = new JFrame("Online Ticketing System");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.add(view, BorderLayout.CENTER);
        frame.setSize(1000, 800);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        browser.loadURL("https://www.esheba.cnsbd.com/");
        
    }//GEN-LAST:event_online_ticketMouseClicked

    private void mobile_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_ticketActionPerformed
        // TODO add your handling code here:
       // this.hide();
    }//GEN-LAST:event_mobile_ticketActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null,"Do you really want to close the app?","Close app",JOptionPane.YES_NO_OPTION,JOptionPane.YES_NO_OPTION);
        if(x == 0){
            System.exit(0);
            System.out.println("Closed");
        }
        else{
            
        }
    }//GEN-LAST:event_exitActionPerformed

    private void login_anotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_anotherActionPerformed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null,"Do you really want to log in with another account?","Login with another acc.",JOptionPane.YES_NO_OPTION,JOptionPane.YES_NO_OPTION);
        if(x == 0){
            Login munna = new Login();
            munna.setVisible(true);
            System.out.println("Closed");
        }
        else{
            
        }
       
        dispose();
        
    }//GEN-LAST:event_login_anotherActionPerformed

    private void mobile_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobile_ticketMouseClicked
        // TODO add your handling code here:
        Browser browser = new Browser();
        BrowserView view = new BrowserView(browser);

        JFrame frame = new JFrame("Bangladesh Railway");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.add(view, BorderLayout.CENTER);
        frame.setSize(500, 400);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        browser.loadURL("C:\\Users\\showkot\\Documents\\NetBeansProjects\\TrainTicket\\Mobile Ticket\\SMS.html");
    }//GEN-LAST:event_mobile_ticketMouseClicked

    private void notice_boardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notice_boardMouseClicked
        // TODO add your handling code here:
        Browser browser = new Browser();
        BrowserView view = new BrowserView(browser);

        JFrame frame = new JFrame("Bangladesh Railway Notice Board");
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.add(view, BorderLayout.CENTER);
        frame.setSize(500, 400);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        browser.loadURL("http://railway.gov.bd/site/view/tenders");
        

    }//GEN-LAST:event_notice_boardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login_another;
    private javax.swing.JButton mobile_ticket;
    private javax.swing.JButton notice_board;
    private javax.swing.JButton online_ticket;
    private javax.swing.JButton train_tracking;
    // End of variables declaration//GEN-END:variables
}
