/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrainTicket;

import com.teamdev.jxbrowser.chromium.a;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.HashMap;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author showkot
 */
public class NewAccount extends javax.swing.JFrame {

    /**
     * Creates new form NewAccount
     */
    public NewAccount() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter (){
            @Override
            public void windowClosing(WindowEvent we) {
               int x = JOptionPane.showConfirmDialog(null,"Do you really want to close the app?","Close",YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
               if(x == JOptionPane.YES_OPTION){
                   we.getWindow().dispose();
                   System.out.println("Closed"); 
               }
               else System.out.println("Still Running");
         }
            
    });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        new_fullname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        new_mobile = new javax.swing.JTextField();
        new_email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        confirm_password = new javax.swing.JPasswordField();
        newsubmit = new javax.swing.JButton();
        new_reset = new javax.swing.JButton();
        new_back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Email");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(165, 246, 92, 34);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mobile");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(165, 316, 92, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(165, 179, 92, 28);

        new_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_fullnameActionPerformed(evt);
            }
        });
        getContentPane().add(new_fullname);
        new_fullname.setBounds(281, 128, 231, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Full Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(165, 128, 92, 33);

        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        getContentPane().add(userName);
        userName.setBounds(281, 182, 231, 28);
        getContentPane().add(new_mobile);
        new_mobile.setBounds(281, 316, 231, 35);
        getContentPane().add(new_email);
        new_email.setBounds(281, 246, 231, 34);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 450, 130, 33);
        getContentPane().add(confirm_password);
        confirm_password.setBounds(280, 450, 231, 33);

        newsubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newsubmit.setText("Submit");
        newsubmit.setBorder(new javax.swing.border.MatteBorder(null));
        newsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsubmitActionPerformed(evt);
            }
        });
        getContentPane().add(newsubmit);
        newsubmit.setBounds(490, 530, 99, 42);

        new_reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        new_reset.setText("Reset");
        new_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_resetActionPerformed(evt);
            }
        });
        getContentPane().add(new_reset);
        new_reset.setBounds(300, 530, 90, 40);

        new_back.setText("Back");
        new_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_backActionPerformed(evt);
            }
        });
        getContentPane().add(new_back);
        new_back.setBounds(160, 530, 55, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(165, 381, 92, 33);
        getContentPane().add(password);
        password.setBounds(281, 381, 231, 33);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void new_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_new_fullnameActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void new_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_resetActionPerformed
        // TODO add your handling code here:
        new_fullname.setText("");
        userName.setText("");
        new_email.setText("");
        new_mobile.setText("");
        password.setText("");
        confirm_password.setText("");
     
        
                
    }//GEN-LAST:event_new_resetActionPerformed

    boolean inValidNumber(String s)
    {
        int len = s.length();
        int flag = 0;
        for(int i = 0; i<len; i++)
        {
            if(s.charAt(i) == '0' || s.charAt(i) == '1'||s.charAt(i) == '2' || s.charAt(i) == '3'||s.charAt(i) == '4' || s.charAt(i) == '5'||s.charAt(i) == '6' || s.charAt(i) == '7'||s.charAt(i) == '8' || s.charAt(i) == '9') flag = 0;
            else {
                flag = 1;
                break;
            }
        }
        if(flag == 1) return true;
        else return false;
        
    }
    boolean isWritable() {
        String user = userName.getText();
        String pass = password.getText();
        HashMap<String, String> authMap = new HashMap<String, String>();
        try {
            FileReader fin = new FileReader("C:\\Users\\showkot\\Documents\\NetBeansProjects\\TrainTicket\\file.txt");
            Scanner sc = new Scanner(fin);
            while (sc.hasNextLine()) {
                String[] parts=sc.nextLine().split(" ");
                authMap.put(parts[0], parts[1]);
            }
        }
         catch (FileNotFoundException e) {

        }

        if (authMap.containsKey(user)) {
            return false;
        }
        return true;
    }
    void fileWrite() throws FileNotFoundException, IOException{
        
        String data = userName.getText() + " " + password.getText();
        String[] all = new String[500];
        int i = 0;
        try {
            FileReader fin = new FileReader("C:\\Users\\showkot\\Documents\\NetBeansProjects\\TrainTicket\\file.txt");
            Scanner sc = new Scanner(fin);
            while (sc.hasNextLine()) {
                all[i]=sc.nextLine();
                i = i+1;
                
            } all[i]=data;
        }
         catch (FileNotFoundException e) {

        }
        
        File fout = new File("file.txt");
        FileOutputStream fos = new FileOutputStream(fout);
        BufferedWriter bufferedWriter = new BufferedWriter(new OutputStreamWriter(fos));
        for(int j = 0; j<=i; j++){
            bufferedWriter.write(all[j]);
            bufferedWriter.newLine();
        }
        bufferedWriter.close();
      
        
        bufferedWriter.close();

    }
    
    private void new_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_backActionPerformed
        // TODO add your handling code here:
        Login palash = new Login();
        palash.setVisible(true);
        dispose();
    }//GEN-LAST:event_new_backActionPerformed

    private void newsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsubmitActionPerformed
        // TODO add your handling code here:
        if(!password.getText().equals(confirm_password.getText()))
        {
           // System.out.println(password.getText());
           // System.out.println(confirm_password.getText());
            JOptionPane.showMessageDialog(null,"Password does not match"); 
        }
        else if(new_fullname.getText().equals(userName.getText()))
        {
            JOptionPane.showMessageDialog(null,"Username and Full name can not be same or empty");
        }
        else if(password.getText().length()<8 || userName.getText().length()<4)
        {
            JOptionPane.showMessageDialog(null,"Password should be at least 8 character and Username should be at least 4 charcter");
        }
        else if(userName.getText().equals(password.getText()))
        {
            JOptionPane.showMessageDialog(null,"Username and Password can not be same");
        }
        else if (inValidNumber(new_mobile.getText())) {
                JOptionPane.showMessageDialog(null,"Mobile number should contain only digits");
             }

        else if(isWritable()){
         try{
            fileWrite();
            Login parvej = new Login();
            parvej.setVisible(true);
            dispose();
         }
         catch(Exception e)
         {
            System.out.println("Exception occured");
         }
            
        }
        else{
            JOptionPane.showMessageDialog(null,"This username already exists");
        }
            
        
     
    }//GEN-LAST:event_newsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton new_back;
    private javax.swing.JTextField new_email;
    private javax.swing.JTextField new_fullname;
    private javax.swing.JTextField new_mobile;
    private javax.swing.JButton new_reset;
    private javax.swing.JButton newsubmit;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
